### PR TITLE
Fix pin numbers

### PR DESCRIPTION
**Pull request by theFork**
All pins had pin number one which was fixed by aziraphale and me.

### CODE REVIEW

**Comment by diggit** [comment]
I am not familiar with this library. Maybe it is intended for connection of array of wires with same functionality. (like all GND wires in ATX PSU,...)

@CarlPoirier is this pin numbering mistake or purpose?

**Comment by hackscribble** [comment]
It would be good to resolve this PR one way or the other.

@evanshultz @jkriege2 @SchrodingersGat   Do you think the comment above is correct, namely that these footprints are intended to connect multiple wires to the same net and hence the pin numbers are the same?

Example footprint ...

image

**Comment by evanshultz** [comment]
It seems like a reasonable guess/assumption, but I have absolutely no idea.

However, if you have one component with multiple holes I've typically seen a single wire assembly with multiple wires bound together. Multiple single wire pads would allow discrete wires. (Certainly crazy tricks can be played with the BOM either way, though.) But in either case, only including single wire pads can always work while having multiple holes will have less applications. I see less usefulness for these multiple-hole footprints.

Also, for wire pads I'd like to include the drill size in millimeter and also the suitable wire gauge in AWG. In different parts of the world one or the other will be most common.

**Comment by SchrodingersGat** [comment]
Not sure either. @theFork are you still around? What is your use-case for these footprints?

**Comment by evanshultz** [comment]
@theFork Hello?

@diggit @hackscribble @SchrodingersGat 
If we don't know why these exist I think it's time to consider if we want them. Is there a reason to keep these footprints? Should they be changed, renamed, removed?

**Comment by theFork** [comment]
@SchrodingersGat My usecase is a generic 3-pin footprint for attaching (soldering) thick wires to. So I would prefer to have three individual pins.

IMHO pin names should not reflect any interconnection. In case someone wishes to connect all pads this can still be done in the schematic.

**Comment by SchrodingersGat** [comment]
@theFork sorry if this did not receive full closure. Please readdress these issues over at https://github.com/kicad/kicad-footprints

**Pull request closed without merging**
